### ISSUE TITLE
Bug with accents authors names

### ISSUE THREAD

**Issue by jodacame** [edgarpf/quote-scraper#1]
Try this:
````javascript
console.log(quoteScraper('Honoré Daumier')); 
````

**Comment by edgarpf** [comment]
Solved. There is no more infinite loop. A new version is already published in npm.

**Comment by jodacame** [comment]
Now return empty quotes... 

***Example:***
````javascript
console.log(quoteScraper('Grégory Baugé')); 
// Output: empty
````

Regards!

**Comment by edgarpf** [comment]
For some reason scraperjs (the library I use to scrap brainyquote site) does not accept accents. I will try to solve this problem later. 

Now, the workaround is remove accents from the name. At least this will avoid infinite loop.

**Comment by edgarpf** [comment]
Hello! Now the problem is solved. I used [**encodeurl**](https://www.npmjs.com/package/encodeurl) library before send the request to the scraper. Now it accepts URL with accents. New version in npm.
